### ISSUE TITLE
Packets Being Sent To The Server. CAUSING THIS MOD TO GET YOU BANNED ON HYPIXEL!

### ISSUE THREAD

**Issue by HerobrineYTgames** [prplz/MemoryFix#7]
So I was using this mod in one of my streams, as it enabled me to do so on the Hypixel server. However, I woke up the next day and was banned by watchdog. So I decided to do a little investigation on this, and I found that packets are being sent to the server pretty consistently. 
Below are two packets that get sent to the server. The ARM_ANIMATION packet is the one being sent the most. The second one happens every time you login  to the server. The first gets sent consistently as you are playing, more specifically, almost every time you hit, place, or break a block.
31.01 15:48:34 [Server] INFO Received ARM_ANIMATION[class=PacketPlayInArmAnimation, id=29] from Deliberating. 
31.01 15:47:37 [Server] INFO Received ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from UNKNOWN[/This is an IP, I don't wanna show it ;)].

I'm not really too experienced with *making* mods and plugins, but I'm pretty experienced with configuring and troubleshooting. I believe this issue is rather crucial to fix as this is causing players to get banned from hypixel, including myself. Which the appeals team denied, as always.

**Comment by prplz** [comment]
Sorry but I'm not sure what you are saying, encryption begin is always sent when you join a server and arm animation is always sent while you play (from any action that makes your arm move)

**Comment by HerobrineYTgames** [comment]
Well, I noticed that this doesn't happen in my console when playing Optifine alone. It seems to only be happening when the Memoryfix mod is running, so I thought it was something with the mod that was a bit off. For some reason the server is receiving these packets in great abundance and watchdog is mistaking them for hacks, thus the ban.

**Comment by prplz** [comment]
You dont send arm animation packet at all without my mod? That makes no sense.

**Comment by HerobrineYTgames** [comment]
I know. It makes no sense to me either, but it's true.

**Comment by HerobrineYTgames** [comment]
I'm going to do a couple more investigations, but the server hasn't been showing that the packets are being received if i'm not using the mod.

**Comment by HerobrineYTgames** [comment]
hmm, interesting. With optifine itself, this time it actually recieved  them.. now im going to try with vanilla minecraft.

**Comment by prplz** [comment]
Arm animation is a normal part of minecraft, as is the encryption begin packet.

**Comment by HerobrineYTgames** [comment]
Then is there a reason as to why Watchdog is banning players using the mod?

**Comment by DeactDev** [comment]
Maybe its not, You ever think about that? maybe you should stop cheating

**Comment by Cryptkeeper** [comment]
Watchdog can't and doesn't ban for this behavior -- it's expected vanilla behavior.

What's your IGN with the bans?

**Comment by HerobrineYTgames** [comment]
I'm not cheating. In fact, I was streaming the day before I was banned.

**Comment by HerobrineYTgames** [comment]
Zephyr991 Is the IGN that has the ban.

**Comment by Cryptkeeper** [comment]
Are you from Poland?

**Comment by HerobrineYTgames** [comment]
No.

**Comment by Cryptkeeper** [comment]
Your account is compromised and is being used by cheaters. Change your Minecraft password along with your email password (and any other accounts using the same password!)

Go to https://hypixel.net/compromised to get your account unbanned.

**Comment by HerobrineYTgames** [comment]
Sure thing!

**Comment by HerobrineYTgames** [comment]
Crypt, you are officially my favorite admin.

**Comment by j-carin** [comment]
that was a wholesome ending

**Comment by HerobrineYTgames** [comment]
hahahah ayyyyyyyyyyyyy 2PI

**Comment by HerobrineYTgames** [comment]
Yep, a wholesome ending for sure! Just waiting for the appeals team to respond.
